arch:
- amd64
- arm64
language: ruby
rvm:
- "2.4"
- "2.5"
- "2.6"
- ruby-head
- jruby-head
sudo: false
cache: bundler
matrix:
  allow_failures:
  - rvm: ruby-head
  - rvm: jruby-head
  fast_finish: true
